"""Soru bankası — tanıtım gününde adaylardan gelmesi beklenen gerçek sorular.

8 kategori. run_question_bank.py bu havuzdan kombinasyonlu senaryolar üretir.
Kaynak: proje sahibinin saha beklentisi listesi (2026-07-16).
"""

QUESTION_BANK: dict[str, list[str]] = {
    "dersler": [
        "Bilgisayar Mühendisliği bölümünde tam olarak ne öğretiliyor?",
        "İlk sınıfta hangi dersler var?",
        "Bölüm sadece kod yazmaktan mı oluşuyor?",
        "Daha önce hiç programlama yapmadım, zorlanır mıyım?",
        "En zor dersler hangileri?",
        "Matematik ve fizik dersleri çok ağır mı?",
        "Derslerin ne kadarı İngilizce?",
        "Hocaların ders anlatımı nasıl?",
        "Dersleri geçmek çok zor mu?",
        "Sınavlar mı, projeler mi daha ağırlıklı?",
        "Öğrenciler bireysel mi yoksa takım hâlinde mi proje yapıyor?",
        "Yapay zekâ, siber güvenlik veya oyun geliştirme gibi alanlarda dersler var mı?",
        "İstediğim alanda seçmeli ders bulabilir miyim?",
        "Bölümün laboratuvarları ve teknik imkânları yeterli mi?",
    ],
    "yeterlilik_kaygisi": [
        "Ben bu bölümü gerçekten yapabilir miyim?",
        "Kodlama bilmiyorsam diğer öğrencilerin gerisinde mi kalırım?",
        "Çok iyi matematik bilmek gerekiyor mu?",
        "Lisede bilgisayarla fazla ilgilenmedim, bu benim için dezavantaj olur mu?",
        "Derslerde başarısız olursam bana yardımcı olacak birileri var mı?",
        "Bölüm çok yoğun olduğu için sosyal hayata zaman kalıyor mu?",
        "İTÜ'de öğrenciler arasında çok fazla rekabet var mı?",
        "Kendimi geliştirmek için okul dışında sürekli çalışmam gerekir mi?",
        "İngilizcem çok iyi değil, dersleri anlamakta zorlanır mıyım?",
        "Bilgisayar başında uzun saatler geçirmek zorunda mıyım?",
    ],
    "kariyer": [
        "İTÜ Bilgisayar Mühendisliği mezunları hangi alanlarda çalışıyor?",
        "Mezun olduktan sonra iş bulmak kolay mı?",
        "Mezunların çalıştığı büyük şirketler hangileri?",
        "Yurt dışında çalışma fırsatı var mı?",
        "İTÜ diploması yurt dışında ne kadar tanınıyor?",
        "Mezunların başlangıç maaşları nasıl?",
        "Yapay zekâ gelişirse bilgisayar mühendislerine ihtiyaç azalır mı?",
        "Yazılım mühendisi olmak için Bilgisayar Mühendisliği okumak şart mı?",
        "Bölüm mezunları sadece yazılımcı mı oluyor?",
        "Siber güvenlik, veri bilimi veya yapay zekâ alanına yönelebilir miyim?",
        "Kendi girişimimi kurmak istersem İTÜ destek sağlıyor mu?",
        "Mezunlarla iletişim kurabileceğimiz bir ağ var mı?",
    ],
    "staj_proje": [
        "Staj bulmak konusunda okul yardımcı oluyor mu?",
        "Öğrenciler kaçıncı sınıfta staj yapmaya başlıyor?",
        "İTÜ'nün şirketlerle bağlantıları güçlü mü?",
        "Öğrenciyken gerçek projelerde çalışabilir miyim?",
        "Teknoparkta veya ARI Teknokent'te çalışma fırsatı var mı?",
        "Hocaların araştırma projelerine katılabilir miyim?",
        "Erasmus veya yurt dışı stajı yapabilir miyim?",
        "Öğrenciler mezun olmadan iş bulabiliyor mu?",
        "Yarışmalara, hackathonlara veya teknoloji takımlarına katılma imkânı var mı?",
    ],
    "karsilastirma": [
        "Neden İTÜ Bilgisayar Mühendisliğini tercih etmeliyim?",
        "İTÜ'nün diğer üniversitelerden farkı nedir?",
        "İTÜ mü, Boğaziçi mi, ODTÜ mü?",
        "İTÜ'de okumanın bana sağlayacağı en büyük avantaj nedir?",
        "Bölümün eğitim kalitesi gerçekten iyi mi?",
        "Üniversitenin adı iş başvurularında fark yaratıyor mu?",
        "İTÜ daha çok teorik mi yoksa uygulamalı eğitim mi veriyor?",
        "İTÜ'nün teknolojik ve akademik imkânları nasıl?",
        "Bilgisayar Mühendisliği bölümünün akreditasyonu var mı?",
        "Öğrenciler bölümden genel olarak memnun mu?",
    ],
    "kampus_sosyal": [
        "Bilgisayar Mühendisliği hangi kampüste?",
        "Ayazağa Kampüsü nasıl bir yer?",
        "Kampüse ulaşım kolay mı?",
        "Yurt imkânları yeterli mi?",
        "İstanbul'da öğrenci olarak yaşamak çok pahalı mı?",
        "Kampüste yemek seçenekleri nasıl?",
        "Üniversitede hangi öğrenci kulüpleri var?",
        "Spor tesisleri ve sosyal alanlar yeterli mi?",
        "Bilgisayar Mühendisliği öğrencilerinin sosyal hayatı var mı?",
        "Kampüs güvenli mi?",
        "Hazırlık öğrencileri de kulüplere ve projelere katılabiliyor mu?",
        "İTÜ'de arkadaş edinmek kolay mı?",
    ],
    "tercih_kabul": [
        "Bölümün taban sıralaması kaç?",
        "Bu sıralamayla bölüme girme ihtimalim var mı?",
        "Kontenjanlar değişti mi?",
        "İngilizce hazırlık zorunlu mu?",
        "Hazırlık atlama sınavı nasıl?",
        "Yatay geçiş veya çift anadal yapabilir miyim?",
        "Bilgisayar Mühendisliği ile başka bir bölümü birlikte okuyabilir miyim?",
        "Burs imkânları var mı?",
        "Tercih listemde İTÜ'yü kaçıncı sıraya yazmalıyım?",
        "Bölüme girdikten sonra başka bir mühendisliğe geçebilir miyim?",
    ],
    # Kullanıcının GERÇEK manuel test üslubu: dolaylı, günlük ağız, yazım gevşek.
    # (Scriptli testler hep "düzgün" cümle kullanıyordu — boşluklar bu yüzden kaçıyordu.)
    "dogal_zorlu": [
        "neticede kaliteli mi bu okul ya",
        "hocam bi anlatsana şu bölümü, ne iş yapıyorsunuz tam olarak",
        "ya bu bölüm gerçekten bi işe yarıyor mu boşuna mı okuycam",
        "devlet okulu iyi olur mu ki özele göre",
        "kanka herkes yazılımcı oldu, doyma noktasına gelmedi mi bu iş",
        "valla bilmiyorum abi ne sorucağımı, sen anlat işte",
        "4 yıl boyunca hayatım bitecek mi burda",
        "puanım tutar mı bilmiyorum ki daha açıklanmadı",
        "annemler karşı çıkıyo napıyım",
        "e peki mezun olunca napıyo bu insanlar gerçekten",
        "oyun mu yapsam yazılım mı öğrensem kararsızım ya",
        "hocalar nasıl, ilgileniyolar mı yoksa sallıyolar mı",
    ],
    "dogal_ifadeler": [
        "Açık konuşur musun, bu bölüm gerçekten çok mu zor?",
        "Ben daha önce hiç kod yazmadım. Buraya gelirsem yapabilir miyim?",
        "İTÜ'ye gelirsem dört yıl boyunca sadece ders mi çalışacağım?",
        "Bilgisayar mühendisliği okumak istiyorum ama yapay zekâ yüzünden geleceğinden emin değilim.",
        "İTÜ'yü seçersem diğer üniversitelere göre ne kazanırım?",
        "Mezun olunca gerçekten iyi bir iş bulabilir miyim?",
        "Burada okuyup Google, Microsoft veya savunma sanayisinde çalışabilir miyim?",
        "İstanbul'da okumak çok masraflı olur mu?",
        "Öğrenciler burada mutlu mu, yoksa herkes sürekli stresli mi?",
        "Ben oyun geliştirmek istiyorum. Bu bölüm bana uygun mu?",
        "Siber güvenlik alanında ilerlemek istiyorum, İTÜ bu konuda iyi mi?",
        "Yurt dışına gitmek istiyorum. İTÜ bana bu konuda ne sağlar?",
        "Bilgisayar mühendisliği mi, yapay zekâ ve veri mühendisliği mi seçmeliyim?",
        "Beni İTÜ Bilgisayar Mühendisliğini seçmeye neden ikna etmelisin?",
    ],
}

# Persona açılışları — soru dizisinin önüne gelir (rank + bağlam verir)
PERSONAS: list[dict] = [
    {"id": "P1_top1000", "opening": "Merhaba, ben Ali. Sıralamam 700 geldi, İTÜ Bilgisayar ilk tercihim ama sorularım var."},
    {"id": "P2_borderline", "opening": "Selam, 1350 sıralamam var. Bilgisayar istiyorum ama emin değilim."},
    {"id": "P3_below", "opening": "Merhaba, 2500 civarı sıralamam var. Bilgisayar zor sanırım ama bir sorayım dedim."},
    {"id": "P4_kaygili", "opening": "merhaba, 1200 sıram var ama açıkçası çok kararsızım ve biraz endişeliyim."},
    {"id": "P5_meraki", "opening": "Selam! Ben Ege, 900 sıralamam var. Teknolojiye çok meraklıyım, her şeyi soracağım."},
    {"id": "P6_pratik", "opening": "Merhaba, 1000 sıram var. Kısa kısa sorularım olacak, net cevaplar istiyorum."},
]
